spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_java?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: 911291

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


  #JPA Settings
  jpa.hibernate.ddl_auto: none